main/urls.py
from django.urls import path

from .views import (
    HomeView,
    ShoeDetailView,
    OrderSummaryView,
    CheckoutView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    success_payment,
    group_members,
)

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ShoeDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug>/', 
         remove_single_item_from_cart,
         name='remove-single-item-from-cart'
    ),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('payment-success/', success_payment, name='payment_success'),
    path('group-members/', group_members, name='group_members'),
]

shoe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear'),
)

LABLE_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)

class Shoe(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABLE_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(blank=True, null=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('main:product', kwargs={
            'slug': self.slug
        })
        
    def get_add_to_cart_url(self):
        return reverse('main:add-to-cart', kwargs={
            'slug': self.slug
        })
        
    def get_remove_from_cart_url(self):
        return reverse('main:remove-from-cart', kwargs={
            'slug': self.slug
        })
    
class OrderShoe(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    ordered = models.BooleanField(default=False)
    shoe = models.ForeignKey(
        Shoe,
        on_delete=models.CASCADE,
    )
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.shoe.name}"
    
    def get_total_item_price(self):
        return self.quantity * self.shoe.price 
    
    def get_total_discount_item_price(self):
        return self.quantity * self.shoe.discount_price
    
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()
    
    def get_final_price(self):
        if self.shoe.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

class Order(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    shoes = models.ManyToManyField(OrderShoe)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.shoes.all():
            total += order_item.get_final_price()
        return total
    

templates/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">
    
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css.map' %}" rel="stylesheet">
    
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
            height: 60vh;
            font-family: Ubuntu;
        }
        
        @media (max-width: 740px) {
            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }
        
        @media (min-width: 800px) and (max-width: 850px) {
            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }
    </style>
</head>

{% include 'navbar.html' %}

<body>
    <div class="mt-5 pt-4">
        {% include 'messages.html' %}
    </div>
    {% block content %} {% endblock content %}
    {% block extra_body %} {% endblock extra_body %}

</body>

</html>

templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Checkout Page{% endblock title %}

{% block content %}
  
  <main>
    <div class="container wow fadeIn">

      <h2 class="my-5 h2 text-center">Checkout</h2>
      <div class="container text-center lead w-50 h-75">
          <p><b>Account Number: </b>01556585955</p>
          <p><b>Account Name: </b>Gauta Talle Mudi</p>
        <p><b>Bank Name: </b>GTB</p>
      </div>
      <a href="{% url 'main:payment_success' %}" class="btn btn-dark w-100">I've sent the money</a>

      <div class="row">

        <div class="col-md-8 mb-4">

          <div class="card">

            <!-- <form method="post" class="card-body">
                {% csrf_token %}

              <div class="md-form mb-5">
                {% comment %} <input type="text" id="address" class="form-control" placeholder="1234 Main St"> {% endcomment %}
                {{ form.street_address }}
                <label for="address" class="">Address</label>
              </div>

              <div class="md-form mb-5">
                {% comment %} <input type="text" id="address-2" class="form-control" placeholder="Apartment or suite"> {% endcomment %}
                {{ form.apartment_address }}
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>

              <div class="row">

                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">Country</label>
                  {% comment %} <select class="custom-select d-block w-100" id="country" required>
                    <option value="">Choose...</option>
                    <option>United States</option>
                  </select> {% endcomment %}
                  {{ form.country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>

                </div>

                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Zip</label>
                  {% comment %} <input type="text" class="form-control" id="zip" placeholder="" required> {% endcomment %}
                  {{ form.zip }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>

              </div>

              <hr>

              <div class="custom-control custom-checkbox">
                <input {% if form.same_shipping_address.value %}checked{% endif %} type="checkbox" name="same_billing_address" class="custom-control-input" id="same-address">
                {% comment %} {{ form.same_billing_address }} {% endcomment %}
                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input {% if form.save_info.value %}checked{% endif %} type="checkbox" class="custom-control-input" name="save_info" id="save-info">
                {% comment %} {{ form.save_info }} {% endcomment %}
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr>

              <div class="d-block my-3">
                  {% for value, name in form.fields.payment_option.choices %}
                    <div class="custom-control custom-radio">
                        <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input"  required>
                        <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                        {% comment %} {{ form.payment_option }} {% endcomment %}
                    </div>
                {% endfor %}
                {% comment %} <div class="custom-control custom-radio">
                  <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="paypal">Paypal</label>
                </div> {% endcomment %}
              </div>
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">

          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product name</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$12</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Second product</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$8</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Third item</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$20</strong>
            </li>
          </ul>

          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form> -->

        </div>

      </div>

    </div>
  </main>

{% include 'footer.html' %}

{% include 'scripts.html' %}
{% endblock content %}

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">


    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2022 Copyright:
      <a href="#" target="_blank"> shoes.com </a>
    </div>
    <!--/.Copyright-->

</footer>

templates/group-members.html
{% extends 'base.html' %}
{% block title %}Group Members{% endblock title %}
{% block content %}
<div class="container">
    <h3 class="pt-5">Group 12 Members</h3>
    <table class="table table-bordered mt-3 table-striped">
        <tr>
            <th>Name</th>
            <th>Registration Number</th>
        </tr>
        <tr>
            <td>Shaharbanu Suleiman</td>
            <td>CST/18/COM/00006</td>
        </tr>
        <tr>
            <td>Abdulmubarak Salihu Yahya</td>
            <td>CST/18/COM/00210</td>
        </tr>
    </table>
    
</div>
{% include "footer.html" %}
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Shoes Home Page{% endblock title %}


{% block content %}

  <main>
    <div class="container">


      <section class="mt-5 text-center mb-4">
        <div class=" mt-5 row wow fadeIn">

        {% for shoe in shoes %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                <img src="{{ shoe.image.url }}" class="card-img-top"
                  alt="">
                <a href="{{ shoe.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  {% comment %} <h5>{{ shoe.get_category_display }}</h5> {% endcomment %}
                </a>
                <h5>
                  <strong>
                    <a href="{{ shoe.get_absolute_url }}" class="dark-grey-text">{{ shoe.title }}
                      <span class="badge badge-pill {{ shoe.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                    {% if shoe.discount_price %}
                        {{ shoe.discount_price }}
                    {% else %}
                        {{ shoe.price }}
                    {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
        {% endfor %}
        </div>
      </section>

    {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% include 'footer.html' %}
{% include 'scripts.html' %}

{% endblock content %}
</body>

</html>

templates/messages.html
{% if messages %}
  {% for message in messages %}
    <div class=alert alert-{{ message.tags }} alert-dismissible fade show role=alert>
      <button class=close type=button data-dismiss=alert aria-lable=Close>
        <span aria-hidden=true>&times;</span>
      </button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <a class="navbar-brand waves-effect" href="{% url 'main:home' %}">
            <strong class="blue-text">SHOES</strong>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                <li><a href="{% url 'main:group_members' %}" class="nav-link waves-effect">Group Members</a></li>
                {% comment %} <li class="nav-item active">
                    <a class="nav-link waves-effect" href="{% url 'main:home' %}" target="">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'main:checkout' %}" target="">Checkout</a>
                </li> {% endcomment %}
            </ul>

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'main:order-summary' %}" class="nav-link waves-effect">
                        <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                        <i class="fas fa-shopping-cart"></i>
                        <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'logout' %}">
                        <span class="clearfix d-none d-sm-inline-block"> Logout </span>
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'login' %}">
                        <span class="clearfix d-none d-sm-inline-block"> Login </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'signup' %}">
                        <span class="clearfix d-none d-sm-inline-block"> Signup </span>
                    </a>
                </li>
                {% endif %}
            </ul>

        </div>

    </div>
</nav>

templates/order_summary.html
{% extends 'base.html' %} {% load static %} {% block title %}E-commerce Home Page{% endblock title %} {% block content %}

<main>
    <div class="container">
        <div class="table-responsive text-nowrap">
            <h2>Order Summary</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Shoe Title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Shoe Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in orders.shoes.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order_item.shoe.title }}</td>
                        <td>{{ order_item.shoe.price }}</td>
                        <td>
                            <a href="{% url 'main:remove-single-item-from-cart' order_item.shoe.slug %}">
                                <i class="fa fa-minus mr-2"></i>
                            </a>
                                {{ order_item.quantity }}
                            <a href="{% url 'main:add-to-cart' order_item.shoe.slug %}">
                                <i class="ml-2 fa fa-plus"></i>
                            </a>
                        </td>
                        <td>
                            {% if order_item.shoe.discount_price %}
                                ${{ order_item.get_total_discount_item_price }}
                                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                            {% else %}
                                ${{ order_item.get_total_item_price }}
                            {% endif %}
                            <a style="color:red;" class="float-right" href="{% url 'main:remove-from-cart' order_item.shoe.slug %}">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5">Your cart is empty</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class="btn btn-primary float-right" href="/">Continue Shopping</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% if orders.get_total %}
                    <tr>
                        <td colspan="4"><b>Order Total</b></td>
                        <td colspan="1"><b>${{ orders.get_total }}</b></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class="btn btn-warning float-right ml-3" href="/checkout/">Proceed To Checkout</a>
                            <a class="btn btn-primary float-right" href="/">Continue Shopping</a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</main>

{% include 'footer.html' %} {% include 'scripts.html' %} {% endblock content %}
</body>

</html>

templates/payment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Checkout Page{% endblock title %}

{% block content %}
  
  <main>
    <div class="container wow fadeIn">

      <h2 class="my-5 h2 text-center">Payment</h2>

      <div class="row">

        <div class="col-md-12 mb-4">

          <div class="card">

            <form method="post" class="card-body">
                {% csrf_token %}
                {{ form|crispy }}
                <input value="Submit" class="btn btn-primary" type="submit" />
            </form>

          </div>

        </div>

      </div>

    </div>
  </main>

{% include 'footer.html' %}

{% include 'scripts.html' %}
{% endblock content %}

templates/product.html
{% extends 'base.html' %}

{% block title %}Product Page{% endblock title %}

{% block content %}

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ shoe.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ shoe.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
                {% if shoe.discount_price %}
                <span class="mr-1">
                    <del>${{ shoe.price }}</del>
                </span>
                <span>${{ shoe.discount_price }}</span>
                {% else %}
                    {{ shoe.price }}
                {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ shoe.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ shoe.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ shoe.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      {% comment %} <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row--> {% endcomment %}

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="#" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="#" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="#" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% include 'footer.html' %}

{% include 'scripts.html' %}
{% endblock content %}

templates/scripts.html
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js.map' %}"></script>
<script type="text/javascript">
    new WOW().init();
</script>

templates/success_payment.html
{% extends 'base.html' %}
{% block title %}Success Payment{% endblock title %}
{% block content %}
<div class="container">
    <div class="pt-5 w-50 h-25 lead">
        <h2>Order Complete</h2>
        <p>
            Dear {{ request.user.username }},<br>
            <b>CONGRATULATIONS,</b> you successfully purchased a property
        </p>
    </div>
</div>
{% include "footer.html" %}
{% endblock content %}